name: attendance
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  bloc: ^9.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_map: ^8.1.1
  flutter_map_math: ^0.2.1
  flutter_modular: ^6.3.4
  image_picker: ^1.1.2
  intl: ^0.20.2
  latlong2: ^0.9.1
  location: ^8.0.0
  path: ^1.9.1
  path_provider: ^2.1.5
  shimmer: ^3.0.0
  supabase: ^2.6.3
  supabase_flutter: ^2.8.4
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
